import NavBar from '@/components/NavBar'
import MainMenu from '@/menus/MainMenu'
import Head from 'next/head'
import AppContextProvider from '../context/AppContext'
import React from 'react';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import SkillChip from '@/components/SkillChip';


export default function Home() {
  return (
    <AppContextProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <NavBar menu={MainMenu} position='relative' />
          <SkillChip />
      </main>
    </AppContextProvider>
  )
}