import NavBar from '@/components/NavBar'
import MainMenu from '@/menus/MainMenu'
import { getThemeTokens } from '@/themes/theme'
import { ThemeProvider, createTheme, useTheme } from '@mui/material'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { createContext, useContext, useMemo, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const ColorModeContext = createContext({ toggleColorMode: () => {} });

export default function ToggleColorMode() {
  const [mode, setMode] = useState<'light' | 'dark'>('light');
  const colorMode = useMemo(
    () => ({
      toggleColorMode: () => {
        setMode((prevMode) => (prevMode === 'light' ? 'dark' : 'light'));
      },
    }),
    [],
  );

  const theme = useMemo(
    () =>
      createTheme(getThemeTokens(mode)),
    [mode],
  );

  return (
    <ColorModeContext.Provider value={colorMode}>
      <ThemeProvider theme={theme}>
        <Home />
      </ThemeProvider>
    </ColorModeContext.Provider>
  );
}

function Home() {
  const theme = useTheme();
  const colorMode = useContext(ColorModeContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar menu={MainMenu} onToggleColorMode={colorMode.toggleColorMode} position='relative' />
      </main>
    </>
  )
}
